//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub server_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auth::Entity",
        from = "Column::DiscordId",
        to = "super::auth::Column::DiscordId",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Auth,
    #[sea_orm(
        belongs_to = "super::server_settings::Entity",
        from = "Column::ServerId",
        to = "super::server_settings::Column::ServerId",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ServerSettings,
}

impl Related<super::auth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auth.def()
    }
}

impl Related<super::server_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
